### ISSUE TITLE
Support for GitHub enterprise hostnames

### ISSUE THREAD

**Issue by dkwon17** [redhat-developer/try-in-dev-spaces-browser-extension#72]
For GitHub enterprise, the hostname for the GitHub instance can vary, ex. `www.github.company-name.com`.

GitHub enterprise documentation for setting the hostname [1]

Today, this extension will not inject the button element on these GitHub instances, because the content script is enabled on `www.github.com/*` urls

https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/blob/3269cbffcf664727bc078d99b38b184ac11e4893/manifest.json#L17-L19

[1] https://docs.github.com/en/enterprise-server@3.5/admin/configuration/configuring-network-settings/configuring-a-hostname

**Comment by dkwon17** [comment]
The main problem is that we need some kind of user input to determine when to inject the Dev Spaces button on different domains. We need user input because just providing `matches` patterns for the button injection won't be sufficient.

To support domains like `www.github.my-company.com`, changing the `matches` pattern to something like `https://github.*.com/*` for the button injection script is not supported. Wildcards can only be for the whole hostname or only for the subdomain (see [doc](https://developer.chrome.com/docs/extensions/mv3/match_patterns/))

Additionally, it may be possible for some GitHub Enterprise urls (or on-prem BitBucket, GitLab, Azure Git urls) to not have a `github` (or some other specific) subdomain.

As a result, we would need the user to provide details about what urls to inject the button for.

### Idea 1
Allow the extension to detect the GitHub webpage and inject the button.

In the extension's options, the user would have to provide the url for their GitHub enterprise instance, and have the extension inject the button for the GitHub instances provided.

<details>
<summary>Mock UX</summary>

![image](https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/assets/83611742/9af5ba92-0d04-4959-ba12-083f22892fba)

</details>

After having the user add their Git instance url, they would need to accept new permissions:

![image](https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/assets/83611742/1a407ce0-4535-4396-81f6-d8e5291eceb4)

### Idea 2
User manually injects the button when on the GitHub project page.

For this idea, the user would invoke the extension by clicking on the extension's icon.


<details>
<summary>Mock UX</summary>

![image](https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/assets/83611742/be2110ee-5469-400e-a413-7d885997bbd2)

![image](https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/assets/83611742/27a8edf6-b635-48d2-bd69-0e25b296293a)


</details>

This does not require an extra permission prompt like in Idea 1, as this method would use activeTab permissions ([doc](https://developer.chrome.com/docs/extensions/mv3/manifest/activeTab/)) instead.

The main drawback for this idea is that the user must click on the extension icon every single time, whenever the user wants to inject the button.

### Idea 3
Don't inject the button at all, and instead provide the button and the options's UI both on a new popup page which is opened by pressing the extension icon.

Since GitHub might change their UI in the future, it might be easier to maintain this extension if the button is provided in a popup page instead:

<details>
<summary>Mock UX</summary>

![image](https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/assets/83611742/d8221fce-e341-4b7a-808a-7a1b84d7c763)


</details>

Since no button is injected (ie, no script runs in the user's webpage), this idea requires the least permissions.
 
 
The main drawback for this idea is that this change the whole UX of the extension.

cc @l0rd @ibuziuk

**Comment by l0rd** [comment]
I like the first idea more. With a little change: instead of "Git instances" I would call it "GitHub Enterprise domains to track".

**Comment by dkwon17** [comment]
Thanks @l0rd for the feedback I've started working on idea 1, but I had a few more thoughts:

For when we eventually support [Add Azure DevOps, GitLab, and BitBucket support ](https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/issues/2) idea 3 offers the simplest solution IMO

It's because for idea 3, since no button is being injected, the extension does not have to care whether the current page is GitHub/GitLab/Bitbucket or not. It would be as simple as:
```
1. User installs web extension
2. User opens project page on GH enterprise / GitLab on-prem etc.
3. User opens extension popup
4. User adds new DS instance if needed
5. User clicks 'Dev Spaces' button in the extension popup
6. Extension reads the current url for the webpage the user is on, and creates factory url
```
without any need to have the user configure git domains. This would technically work for any git service domain (on-prem or not) for any git service

We can go ahead with idea 1, but making the extension simpler on the development side (by not having Git service detection and injection logic) as well as the ability to create a workspace within any git domain are great improvements IMO. It would also solve issues like https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/issues/32 https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/issues/54 https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/issues/55 https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/issues/59 https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/issues/62 https://github.com/redhat-developer/try-in-dev-spaces-browser-extension/issues/63

**Comment by l0rd** [comment]
You are right, idea 3 would make things simpler for us. I am afraid that we will lose in usability though. We should ask users what they think about it. Maybe you can ask in our internal google chat?
